#ifndef BRONZESTYLEPLUGIN_GLOBAL_H
#define BRONZESTYLEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BRONZESTYLEPLUGIN_LIBRARY)
#  define BRONZESTYLEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BRONZESTYLEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BRONZESTYLEPLUGIN_GLOBAL_H
